/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as newNftSol from "./NewNFT.sol";
export { Lock__factory } from "./Lock__factory";
export { MyNFT__factory } from "./MyNFT__factory";
