/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as newNftSol from "./NewNFT.sol";
export type { newNftSol };
export type { Lock } from "./Lock";
export type { MyNFT } from "./MyNFT";
